name: Checkstyle

on: [push, pull_request]

jobs:
  checkstyle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run CheckstyleMain
        run: |
          cd app
          ./gradlew checkstyleMain
      - name: Run Checkstyle
        run: |
          cd app
          ./gradlew checkstyleTest

      - name: List files for debugging
        run: ls -la

      - name: Build with Gradle
        run: |
          cd app
          ./gradlew build

      - name: Publish code coverage
        uses: paambaati/codeclimate-action@v9.0.0
        env:
          CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
          JACOCO_SOURCE_PATH: ${{github.workspace}}/app/src/main/java
        with:
          coverageCommand: |
           cd app
           ./gradlew jacocoTestReport  # Используем gradlew для генерации отчета
          coverageLocations: ${{github.workspace}}/app/build/reports/jacoco/test/jacocoTestReport.xml:jacoco
