name: Checkstyle

on: [push, pull_request]

jobs:
  checkstyle:
    runs-on: ubuntu-latest
    steps:
      - name: Run Checkstyle
        working-directory: ~/app
        run: ./gradlew checkstyleMain
