name: Checkstyle

on: [push, pull_request]

jobs:
  checkstyle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Checkstyle
        run: |
          cd app
          ./gradlew checkstyleMain
      - name: List files for debugging
        run: ls -la
